update

diff --git a/docker/ruby/Dockerfile b/docker/ruby/Dockerfile
--- a/docker/ruby/Dockerfile
+++ b/docker/ruby/Dockerfile
@@ -1,6 +1,6 @@
 FROM ruby:3.4.4-slim-bookworm AS base
 
-RUN apt update && apt --fix-missing install -y build-essential pkg-config libpq-dev curl cmake libssl-dev libyaml-dev\
+RUN apt update && apt --fix-missing install -y build-essential pkg-config bash curl cmake libssl-dev libengine-gost-openssl \
      && rm -rf /var/lib/apt/lists/*
 
 RUN echo 'gem: --no-document' >> ~/.gemrc
@@ -12,24 +12,11 @@ COPY Gemfile* /app/
 RUN bundle install --jobs $(nproc) --retry=3 && \
     bundle clean --force && rm -rf /usr/local/bundle/cache/*
 
-COPY . /app
-
-ENV RACK_ENV=production NODE_ENV=production
-RUN rake -T | grep 'rake build' && rake build || echo 'no build task'
-
-# used in .gitlab-ci.yml Tests.
-FROM base AS tests
-# COPY . . required test fixtures
-CMD bundle exec rspec
-
 FROM ruby:3.4.4-slim-bookworm AS deploy
-RUN apt update && apt install --fix-missing -y bash curl libssl-dev bash curl wget libpq-dev libyaml-0-2\
+RUN apt update && apt install --fix-missing -y bash curl libssl-dev libengine-gost-openssl \
      && rm -rf /var/lib/apt/lists/*
 
 COPY --from=base /usr/local/bundle /usr/local/bundle
-
-# Force start & wait test Stage
-# COPY --from=tests /app/src/spec/results /app/src/spec/results
 
 COPY . /app
 
@@ -41,6 +28,6 @@ ENV RUBY_YJIT_ENABLE=1 \
 WORKDIR /app
 
 # --start_period=5s (Unknown flag: start_period)
-HEALTHCHECK --interval=15s --timeout=2s --retries=3 CMD curl --fail http://127.0.0.1:$PORT/healthcheck || exit 1
-CMD bundle exec rackup -o 0.0.0.0 -p $PORT -s falcon
+# HEALTHCHECK --interval=15s --timeout=2s --retries=3 CMD curl --fail http://127.0.0.1:$PORT/healthcheck || exit 1
+CMD ls && bundle exec rackup -o 0.0.0.0 -p $PORT -s falcon
 # docker-compose build --progress plain
